name = "ndigirigijohn/workshop-examples"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ndigirigijohn/workshop-examples'"

[repository]
user = "ndigirigijohn"
project = "workshop-examples"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.10"
source = "github"

[config]